version: "3.7"
services:
  web1:
    build: ./quote_gen
    container_name: gen
    ports:
      - "8000:8000"
  web2:
    build: ./quote_disp
    container_name: disp
    ports:
      - "8001:8001"
    depends_on:
      - web1
